// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mspgnsoggvecnkdvqefu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcGduc29nZ3ZlY25rZHZxZWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzk5NzMsImV4cCI6MjA3MDgxNTk3M30.TG3WcSSDNTWLrWYYBpoKItX3ztKDjliU9e-Wee9F0ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});